<?php

declare(strict_types=1);

namespace Mupy\TOConline\DTO;

final class SalesDocumentLine implements DataTransferObject
{
    public function __construct(
        public readonly int $id,
        public readonly int $itemId,
        public readonly ?string $itemCode,
        public readonly string $description,
        public readonly float $amount,
        public readonly float $unitPrice,
        public readonly float $quantity,
        public readonly ?string $taxCode,
        public readonly ?float $taxPercentage,
        public readonly ?float $taxAmount,
        public readonly ?float $settlementAmount,
        public readonly float $settlementPercentage,
        public readonly ?string $exemptionReason,
        public readonly ?string $createdAt,
        public readonly ?string $updatedAt,
        public readonly ?string $taxCountryRegion,
        public readonly ?bool $itemUnitPriceIncludesVat,
        public readonly float $netAmount,
        public readonly float $netUnitPrice,
        public readonly ?float $netTaxAmount,
        public readonly ?string $date,
        public readonly ?float $retentionValue,
        public readonly ?float $pendingTotal,
        public readonly ?float $pendingRetentionValue,
        public readonly ?bool $locked,
        public readonly ?float $baseCurrencyAmount,
        public readonly ?float $baseCurrencyUnitPrice,
        public readonly ?float $baseCurrencyTaxAmount,
        public readonly ?float $baseCurrencyNetUnitPrice,
        public readonly ?float $baseCurrencyNetAmount,
        public readonly ?float $baseCurrencySettlementWithoutTax,
        public readonly ?string $originalDocumentNo,
        public readonly ?float $netSettlementAmount,
        public readonly float $netAmountWithHeaderSettlement,
        public readonly float $amountWithHeaderSettlement,
        public readonly float $settlementWithTax,
        public readonly float $settlementWithoutTax,
        public readonly ?float $baseCurrencySettlementWithTax,
        public readonly ?string $itemType,
        public readonly ?float $pendingQuantity,
        public readonly ?float $importedQuantity,
        public readonly ?string $settlementExpression,
        public readonly ?int $taxDescriptorId,
        public readonly ?int $documentId,
        public readonly ?int $serviceId,
        public readonly ?int $taxId,
        public readonly ?int $unitOfMeasureId,
        public readonly array $rawData = []
    ) {}

    public static function fromArray(array $data): self
    {
        return new self(
            id: (int) ($data['id'] ?? 0),
            itemId: (int) ($data['item_id'] ?? 0),
            itemCode: $data['item_code'] ?? null,
            description: (string) ($data['description'] ?? ''),
            amount: (float) ($data['amount'] ?? 0.0),
            unitPrice: (float) ($data['unit_price'] ?? 0.0),
            quantity: (float) ($data['quantity'] ?? 0.0),
            taxCode: $data['tax_code'] ?? null,
            taxPercentage: isset($data['tax_percentage']) ? (float) $data['tax_percentage'] : null,
            taxAmount: isset($data['tax_amount']) ? (float) $data['tax_amount'] : null,
            settlementAmount: isset($data['settlement_amount']) ? (float) $data['settlement_amount'] : null,
            settlementPercentage: (float) ($data['settlement_percentage'] ?? 0.0),
            exemptionReason: $data['exemption_reason'] ?? null,
            createdAt: $data['created_at'] ?? null,
            updatedAt: $data['updated_at'] ?? null,
            taxCountryRegion: $data['tax_country_region'] ?? null,
            itemUnitPriceIncludesVat: isset($data['item_unit_price_includes_vat']) ? (bool) $data['item_unit_price_includes_vat'] : null,
            netAmount: (float) ($data['net_amount'] ?? 0.0),
            netUnitPrice: (float) ($data['net_unit_price'] ?? 0.0),
            netTaxAmount: isset($data['net_tax_amount']) ? (float) $data['net_tax_amount'] : null,
            date: $data['date'] ?? null,
            retentionValue: isset($data['retention_value']) ? (float) $data['retention_value'] : null,
            pendingTotal: isset($data['pending_total']) ? (float) $data['pending_total'] : null,
            pendingRetentionValue: isset($data['pending_retention_value']) ? (float) $data['pending_retention_value'] : null,
            locked: isset($data['locked']) ? (bool) $data['locked'] : null,
            baseCurrencyAmount: isset($data['base_currency_amount']) ? (float) $data['base_currency_amount'] : null,
            baseCurrencyUnitPrice: isset($data['base_currency_unit_price']) ? (float) $data['base_currency_unit_price'] : null,
            baseCurrencyTaxAmount: isset($data['base_currency_tax_amount']) ? (float) $data['base_currency_tax_amount'] : null,
            baseCurrencyNetUnitPrice: isset($data['base_currency_net_unit_price']) ? (float) $data['base_currency_net_unit_price'] : null,
            baseCurrencyNetAmount: isset($data['base_currency_net_amount']) ? (float) $data['base_currency_net_amount'] : null,
            baseCurrencySettlementWithoutTax: isset($data['base_currency_settlement_without_tax']) ? (float) $data['base_currency_settlement_without_tax'] : null,
            originalDocumentNo: $data['original_document_no'] ?? null,
            netSettlementAmount: isset($data['net_settlement_amount']) ? (float) $data['net_settlement_amount'] : null,
            netAmountWithHeaderSettlement: (float) ($data['net_amount_with_header_settlement'] ?? 0.0),
            amountWithHeaderSettlement: (float) ($data['amount_with_header_settlement'] ?? 0.0),
            settlementWithTax: (float) ($data['settlement_with_tax'] ?? 0.0),
            settlementWithoutTax: (float) ($data['settlement_without_tax'] ?? 0.0),
            baseCurrencySettlementWithTax: isset($data['base_currency_settlement_with_tax']) ? (float) $data['base_currency_settlement_with_tax'] : null,
            itemType: $data['item_type'] ?? null,
            pendingQuantity: isset($data['pending_quantity']) ? (float) $data['pending_quantity'] : null,
            importedQuantity: isset($data['imported_quantity']) ? (float) $data['imported_quantity'] : null,
            settlementExpression: $data['settlement_expression'] ?? null,
            taxDescriptorId: isset($data['tax_descriptor_id']) ? (int) $data['tax_descriptor_id'] : null,
            documentId: isset($data['document_id']) ? (int) $data['document_id'] : null,
            serviceId: isset($data['service_id']) ? (int) $data['service_id'] : null,
            taxId: isset($data['tax_id']) ? (int) $data['tax_id'] : null,
            unitOfMeasureId: isset($data['unit_of_measure_id']) ? (int) $data['unit_of_measure_id'] : null,
            rawData: $data
        );
    }
}
